# Generated by Django 5.0.7 on 2024-07-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
